### ISSUE TITLE
Validation problems

### ISSUE THREAD

**Issue by JulieAlbers** [JulieAlbers/content-semantics#1]
@thomasjbradley
A few problems I can't seem to figure out:
-Markbot says the time elements aren't in the right format for both line 24 and 59. Are there attributes that have to go with the time tag to fix that? I don't think I should be changing the content to fix it.
-In the descriptive list, it's saying the data elements are missing attributes, is that something that refers to the kind of measurement each piece of data is? No attributes were listed for ol on the tags cheat sheet
-And something is up with the p tag in line 27, I'm not sure what Markbot is trying to tell me...

**Comment by JulieAlbers** [comment]
fixed paragraph tag issue in line 27

**Comment by thomasjbradley** [comment]
> - Markbot says the time elements aren't in the right format for both line 24 and 59. Are there attributes that have to go with the time tag to fix that? I don't think I should be changing the content to fix it.

Yeah, the `<time>` element needs a `datetime` attribute, like this:

``` html
<time datetime="">…</time>
```

The `datetime` attribute is a purely computer readable format.
You can see a couple examples here:
https://learn-the-web.algonquindesign.ca/topics/html-semantics/#more-specific-elements

---

> - In the descriptive list, it's saying the data elements are missing attributes, is that something that refers to the kind of measurement each piece of data is? No attributes were listed for ol on the tags cheat sheet

Similar to the `<time>` element the `<data>` element needs a `value` attribute, that defines the information in a purely computer readable format:

``` html
<data value="">…</data>
```

Examples at the same link above.

**Comment by JulieAlbers** [comment]
So if `<time datetime="P55D">` means a duration of 55 days, how would you represent a range of time, like 55 to 65 days? Or would each number have it's own `<time>` tag and `datetime` attribute?

**Comment by thomasjbradley** [comment]
> So if `<time datetime="P55D">` means a duration of 55 days

Yep, totally!

> how would you represent a range of time, like 55 to 65 days? Or would each number have it's own `<time>` tag and `datetime` attribute?

Using two `<time>` tags is a perfectly good solution, or another solution would be something like this:

``` html
<time datetime="P55D">55 to 65 days</time>
```

Where we only reference one of the time periods in the `datetime` attribute.
